.julia_build_and_test:
  image: julia:1.0
  script:
    - julia --project='@.' -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    - julia --project=test/coverage test/coverage/coverage-summary.jl
  coverage: /Test Coverage (\d+\.\d+%)/

Julia 1.0:
  extends: .julia_build_and_test
  image: julia:1.0

Julia 1.1:
  extends: .julia_build_and_test
  image: julia:1.1

Julia 1.2:
  extends: .julia_build_and_test
  image: julia:1.2

Julia 1.3:
  extends: .julia_build_and_test
  image: julia:1.3
  
Julia 1.4:
  extends: .julia_build_and_test
  image: julia:1.4

pages:
  image: julia:1.0
  stage: deploy
  before_script:
    - apt update -y && apt install -y git
  script:
    - julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - master
